# CI de Nivel 01 - Disparo manual a partir de um click

# nome do nosso 'pipeline'
name: 'Execução Manual'

# regras de disparo (gatilhos/triggers)
# gatinho de exec manual = workflow_dispatch

on: 
  workflow_dispatch:

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:

   # maquina que o job vai executar
   runs-on: ubuntu-latest

# passos do script de build
steps:
   # clone do projeto
   - uses: actions/checkout@v4

   # instalacao do node
   - uses: actions/setup-node@v4
     with: 
       node-version: 22.x
   
   # instalacao do Yarn
   - name: Instalando Yarn
     run: npm install -g Yarn

   # instalcao das dependencias
   - name: Instalando dependencias
     run: yarn 

   # instalacao do playwright
   - name: Instalando playwright
     run: yarn playwright install

   # executar os testes e2e
   - name: Executando Testes e2e
     run: yarn run e2e  
